"""
Script para poblar SuperLipidDB_PA (LipidBlast, LIPID MAPS, SwissLipids, HMDB).
Genera registros curados y estandarizados para las principales clases de lípidos en lipidómica.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from gestor_lipidos import CSV_FILE, DB_FILE, DB_NAME, JSON_FILE, exportar_archivos, inicializar_bd, insertar_lipido

# Catálogo curado integrado de especies lipídicas representativas
LIPIDOS_CATALOGO = [
    # --- FOSFATIDILCOLINAS (PC) ---
    {
        "abreviatura": "PC(32:0)",
        "abreviatura_lipidblast": "PC 32:0",
        "abreviatura_cadenas": "PC 16:0/16:0",
        "nombre_comun": "Dipalmitoilfosfatidilcolina (DPPC)",
        "nombre_sistematico": "1,2-dihexadecanoyl-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C40H80NO8P",
        "masa_exacta": 733.5622,
        "lipidmaps_id": "LMGP01010002",
        "swisslipids_id": "SLM:000000557",
        "hmdb_id": "HMDB0000564",
        "chebi_id": "CHEBI:16127",
        "pubchem_cid": "443015",
        "smiles": "CCCCCCCCCCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CCCCCCCCCCCCCCC",
        "inchi_key": "KILNVBNDVJNVNK-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 32:0", "LipidBlast"), ("PC(16:0/16:0)", "IUPAC"), ("DPPC", "Comun"), ("16:0-16:0 PC", "Dialect")]
    },
    {
        "abreviatura": "PC(34:1)",
        "abreviatura_lipidblast": "PC 34:1",
        "abreviatura_cadenas": "PC 16:0/18:1",
        "nombre_comun": "1-palmitoil-2-oleoilfosfatidilcolina (POPC)",
        "nombre_sistematico": "1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C42H82NO8P",
        "masa_exacta": 759.5778,
        "lipidmaps_id": "LMGP01010001",
        "swisslipids_id": "SLM:000000571",
        "hmdb_id": "HMDB0007873",
        "chebi_id": "CHEBI:72986",
        "pubchem_cid": "52922943",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "IZGAXEWHRFTGIW-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 34:1", "LipidBlast"), ("PC 16:0_18:1", "LipidBlast"), ("POPC", "Comun"), ("PC(16:0/18:1)", "IUPAC")]
    },
    {
        "abreviatura": "PC(34:2)",
        "abreviatura_lipidblast": "PC 34:2",
        "abreviatura_cadenas": "PC 16:0/18:2",
        "nombre_comun": "1-palmitoil-2-linoleoilfosfatidilcolina",
        "nombre_sistematico": "1-hexadecanoyl-2-(9Z,12Z-octadecadienoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C42H80NO8P",
        "masa_exacta": 757.5622,
        "lipidmaps_id": "LMGP01010005",
        "swisslipids_id": "SLM:000000572",
        "hmdb_id": "HMDB0007874",
        "chebi_id": "CHEBI:73010",
        "pubchem_cid": "52922944",
        "smiles": "CCCCC/C=C\\C/C=C\\CCCCCCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "MTHSVFGVTMLTFR-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 34:2", "LipidBlast"), ("PC(16:0/18:2)", "IUPAC"), ("PLPC", "Comun")]
    },
    {
        "abreviatura": "PC(36:1)",
        "abreviatura_lipidblast": "PC 36:1",
        "abreviatura_cadenas": "PC 18:0/18:1",
        "nombre_comun": "1-estearoil-2-oleoilfosfatidilcolina (SOPC)",
        "nombre_sistematico": "1-octadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C44H86NO8P",
        "masa_exacta": 787.6091,
        "lipidmaps_id": "LMGP01010006",
        "swisslipids_id": "SLM:000000589",
        "hmdb_id": "HMDB0007886",
        "chebi_id": "CHEBI:73024",
        "pubchem_cid": "52922949",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "YHQXMKFFFLXYTA-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 36:1", "LipidBlast"), ("PC(18:0/18:1)", "IUPAC"), ("SOPC", "Comun")]
    },
    {
        "abreviatura": "PC(36:2)",
        "abreviatura_lipidblast": "PC 36:2",
        "abreviatura_cadenas": "PC 18:1/18:1",
        "nombre_comun": "1,2-dioleoilfosfatidilcolina (DOPC)",
        "nombre_sistematico": "1,2-di-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C44H84NO8P",
        "masa_exacta": 785.5935,
        "lipidmaps_id": "LMGP01010003",
        "swisslipids_id": "SLM:000000590",
        "hmdb_id": "HMDB0000574",
        "chebi_id": "CHEBI:73860",
        "pubchem_cid": "5497103",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
        "inchi_key": "WTJKGGKOPKCXLL-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 36:2", "LipidBlast"), ("PC(18:1/18:1)", "IUPAC"), ("DOPC", "Comun"), ("PC 18:0_18:2", "Isomero")]
    },
    {
        "abreviatura": "PC(36:4)",
        "abreviatura_lipidblast": "PC 36:4",
        "abreviatura_cadenas": "PC 16:0/20:4",
        "nombre_comun": "1-palmitoil-2-araquidonoilfosfatidilcolina",
        "nombre_sistematico": "1-hexadecanoyl-2-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C44H78NO8P",
        "masa_exacta": 781.5465,
        "lipidmaps_id": "LMGP01010008",
        "swisslipids_id": "SLM:000000592",
        "hmdb_id": "HMDB0007888",
        "chebi_id": "CHEBI:73030",
        "pubchem_cid": "52922952",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "CYVIHQURZZKCSB-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 36:4", "LipidBlast"), ("PC(16:0/20:4)", "IUPAC"), ("PAPC", "Comun")]
    },
    {
        "abreviatura": "PC(38:4)",
        "abreviatura_lipidblast": "PC 38:4",
        "abreviatura_cadenas": "PC 18:0/20:4",
        "nombre_comun": "1-estearoil-2-araquidonoilfosfatidilcolina (SAPC)",
        "nombre_sistematico": "1-octadecanoyl-2-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C46H82NO8P",
        "masa_exacta": 809.5778,
        "lipidmaps_id": "LMGP01010010",
        "swisslipids_id": "SLM:000000609",
        "hmdb_id": "HMDB0007901",
        "chebi_id": "CHEBI:73041",
        "pubchem_cid": "52922956",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "VZJHYYVTCSZJBG-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 38:4", "LipidBlast"), ("PC(18:0/20:4)", "IUPAC"), ("SAPC", "Comun")]
    },
    {
        "abreviatura": "PC(38:5)",
        "abreviatura_lipidblast": "PC 38:5",
        "abreviatura_cadenas": "PC 18:0/20:5",
        "nombre_comun": "1-estearoil-2-eicosapentaenoilfosfatidilcolina",
        "nombre_sistematico": "1-octadecanoyl-2-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C46H80NO8P",
        "masa_exacta": 807.5622,
        "lipidmaps_id": "LMGP01010011",
        "swisslipids_id": "SLM:000000610",
        "hmdb_id": "HMDB0007902",
        "chebi_id": "CHEBI:73042",
        "pubchem_cid": "52922957",
        "smiles": "CC/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "HBRZDYJAGMOGQU-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 38:5", "LipidBlast"), ("PC(18:0/20:5)", "IUPAC")]
    },
    {
        "abreviatura": "PC(38:6)",
        "abreviatura_lipidblast": "PC 38:6",
        "abreviatura_cadenas": "PC 16:0/22:6",
        "nombre_comun": "1-palmitoil-2-docosahexaenoilfosfatidilcolina",
        "nombre_sistematico": "1-hexadecanoyl-2-(4Z,7Z,10Z,13Z,16Z,19Z-docosahexaenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C46H78NO8P",
        "masa_exacta": 805.5465,
        "lipidmaps_id": "LMGP01010012",
        "swisslipids_id": "SLM:000000611",
        "hmdb_id": "HMDB0007903",
        "chebi_id": "CHEBI:73043",
        "pubchem_cid": "52922958",
        "smiles": "CC/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\CCC(=O)OC(COC(=O)CCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "XGNYDFFQGGBGFF-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 38:6", "LipidBlast"), ("PC(16:0/22:6)", "IUPAC"), ("PDPC", "Comun")]
    },
    {
        "abreviatura": "PC(40:6)",
        "abreviatura_lipidblast": "PC 40:6",
        "abreviatura_cadenas": "PC 18:0/22:6",
        "nombre_comun": "1-estearoil-2-docosahexaenoilfosfatidilcolina (SDPC)",
        "nombre_sistematico": "1-octadecanoyl-2-(4Z,7Z,10Z,13Z,16Z,19Z-docosahexaenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Diacylglycerophosphocholines [GP0101]",
        "formula": "C48H84NO8P",
        "masa_exacta": 833.5935,
        "lipidmaps_id": "LMGP01010821",
        "swisslipids_id": "SLM:000000628",
        "hmdb_id": "HMDB0007917",
        "chebi_id": "CHEBI:73056",
        "pubchem_cid": "52922967",
        "smiles": "CC/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\CCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "KHYUCPCRSZWAGU-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PC 40:6", "LipidBlast"), ("PC(18:0/22:6)", "IUPAC"), ("SDPC", "Comun")]
    },

    # --- LISOFOSFATIDILCOLINAS (LPC / lysoPC) ---
    {
        "abreviatura": "LPC(16:0)",
        "abreviatura_lipidblast": "lysoPC 16:0",
        "abreviatura_cadenas": "LPC 16:0",
        "nombre_comun": "1-palmitoil-sn-glicero-3-fosfocolina",
        "nombre_sistematico": "1-hexadecanoyl-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Monoacylglycerophosphocholines [GP0105]",
        "formula": "C24H50NO7P",
        "masa_exacta": 495.3325,
        "lipidmaps_id": "LMGP01050001",
        "swisslipids_id": "SLM:000000456",
        "hmdb_id": "HMDB0010382",
        "chebi_id": "CHEBI:34372",
        "pubchem_cid": "468784",
        "smiles": "CCCCCCCCCCCCCCCC(=O)OCC(O)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "SRIGYWIRGWYDTF-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("lysoPC 16:0", "LipidBlast"), ("LPC 16:0", "Shorthand"), ("1-palmitoyl-LPC", "Comun")]
    },
    {
        "abreviatura": "LPC(18:0)",
        "abreviatura_lipidblast": "lysoPC 18:0",
        "abreviatura_cadenas": "LPC 18:0",
        "nombre_comun": "1-estearoil-sn-glicero-3-fosfocolina",
        "nombre_sistematico": "1-octadecanoyl-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Monoacylglycerophosphocholines [GP0105]",
        "formula": "C26H54NO7P",
        "masa_exacta": 523.3638,
        "lipidmaps_id": "LMGP01050002",
        "swisslipids_id": "SLM:000000458",
        "hmdb_id": "HMDB0010384",
        "chebi_id": "CHEBI:34374",
        "pubchem_cid": "468785",
        "smiles": "CCCCCCCCCCCCCCCCC(=O)OCC(O)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "GZDFOWWVQCSBMT-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("lysoPC 18:0", "LipidBlast"), ("LPC 18:0", "Shorthand")]
    },
    {
        "abreviatura": "LPC(18:1)",
        "abreviatura_lipidblast": "lysoPC 18:1",
        "abreviatura_cadenas": "LPC 18:1(9Z)",
        "nombre_comun": "1-oleoil-sn-glicero-3-fosfocolina",
        "nombre_sistematico": "1-(9Z-octadecenoyl)-sn-glycero-3-phosphocholine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphocholines [GP01]",
        "subclase": "Monoacylglycerophosphocholines [GP0105]",
        "formula": "C26H52NO7P",
        "masa_exacta": 521.3481,
        "lipidmaps_id": "LMGP01050003",
        "swisslipids_id": "SLM:000000459",
        "hmdb_id": "HMDB0010385",
        "chebi_id": "CHEBI:34375",
        "pubchem_cid": "468786",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(O)COP(=O)([O-])OCC[N+](C)(C)C",
        "inchi_key": "BZZVOAXBZJIIEB-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("lysoPC 18:1", "LipidBlast"), ("LPC 18:1", "Shorthand")]
    },

    # --- FOSFATIDILETANOLAMINAS (PE) ---
    {
        "abreviatura": "PE(34:1)",
        "abreviatura_lipidblast": "PE 34:1",
        "abreviatura_cadenas": "PE 16:0/18:1",
        "nombre_comun": "1-palmitoil-2-oleoilfosfatidiletanolamina (POPE)",
        "nombre_sistematico": "1-hexadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phosphoethanolamine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoethanolamines [GP02]",
        "subclase": "Diacylglycerophosphoethanolamines [GP0201]",
        "formula": "C39H76NO8P",
        "masa_exacta": 717.5309,
        "lipidmaps_id": "LMGP02010001",
        "swisslipids_id": "SLM:000001185",
        "hmdb_id": "HMDB0008912",
        "chebi_id": "CHEBI:73754",
        "pubchem_cid": "52922980",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCC)COP(=O)(O)OCCN",
        "inchi_key": "NKGMNNDOQPGGIP-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PE 34:1", "LipidBlast"), ("PE 16:0_18:1", "LipidBlast"), ("POPE", "Comun"), ("PE(16:0/18:1)", "IUPAC")]
    },
    {
        "abreviatura": "PE(36:2)",
        "abreviatura_lipidblast": "PE 36:2",
        "abreviatura_cadenas": "PE 18:1/18:1",
        "nombre_comun": "1,2-dioleoilfosfatidiletanolamina (DOPE)",
        "nombre_sistematico": "1,2-di-(9Z-octadecenoyl)-sn-glycero-3-phosphoethanolamine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoethanolamines [GP02]",
        "subclase": "Diacylglycerophosphoethanolamines [GP0201]",
        "formula": "C41H78NO8P",
        "masa_exacta": 743.5465,
        "lipidmaps_id": "LMGP02010003",
        "swisslipids_id": "SLM:000001204",
        "hmdb_id": "HMDB0008929",
        "chebi_id": "CHEBI:64612",
        "pubchem_cid": "5497105",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(COP(=O)(O)OCCN)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
        "inchi_key": "DPGZVUQOENNZMC-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PE 36:2", "LipidBlast"), ("PE(18:1/18:1)", "IUPAC"), ("DOPE", "Comun")]
    },
    {
        "abreviatura": "PE(38:4)",
        "abreviatura_lipidblast": "PE 38:4",
        "abreviatura_cadenas": "PE 18:0/20:4",
        "nombre_comun": "1-estearoil-2-araquidonoilfosfatidiletanolamina (SAPE)",
        "nombre_sistematico": "1-octadecanoyl-2-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sn-glycero-3-phosphoethanolamine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoethanolamines [GP02]",
        "subclase": "Diacylglycerophosphoethanolamines [GP0201]",
        "formula": "C43H78NO8P",
        "masa_exacta": 767.5465,
        "lipidmaps_id": "LMGP02010010",
        "swisslipids_id": "SLM:000001223",
        "hmdb_id": "HMDB0008947",
        "chebi_id": "CHEBI:73769",
        "pubchem_cid": "52922994",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)(O)OCCN",
        "inchi_key": "VZJHYYVTCSZJBG-PE-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PE 38:4", "LipidBlast"), ("PE(18:0/20:4)", "IUPAC"), ("SAPE", "Comun")]
    },

    # --- FOSFATIDILSERINAS (PS) ---
    {
        "abreviatura": "PS(36:1)",
        "abreviatura_lipidblast": "PS 36:1",
        "abreviatura_cadenas": "PS 18:0/18:1",
        "nombre_comun": "1-estearoil-2-oleoilfosfatidilserina (SOPS)",
        "nombre_sistematico": "1-octadecanoyl-2-(9Z-octadecenoyl)-sn-glycero-3-phospho-L-serine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoserines [GP03]",
        "subclase": "Diacylglycerophosphoserines [GP0301]",
        "formula": "C42H82NO10P",
        "masa_exacta": 789.5520,
        "lipidmaps_id": "LMGP03010006",
        "swisslipids_id": "SLM:000001804",
        "hmdb_id": "HMDB0011500",
        "chebi_id": "CHEBI:73801",
        "pubchem_cid": "52923010",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)(O)OCC(N)C(=O)O",
        "inchi_key": "QVPZJLYQWNWLNR-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PS 36:1", "LipidBlast"), ("PS(18:0/18:1)", "IUPAC"), ("SOPS", "Comun")]
    },
    {
        "abreviatura": "PS(38:4)",
        "abreviatura_lipidblast": "PS 38:4",
        "abreviatura_cadenas": "PS 18:0/20:4",
        "nombre_comun": "1-estearoil-2-araquidonoilfosfatidilserina (SAPS)",
        "nombre_sistematico": "1-octadecanoyl-2-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sn-glycero-3-phospho-L-serine",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoserines [GP03]",
        "subclase": "Diacylglycerophosphoserines [GP0301]",
        "formula": "C44H78NO10P",
        "masa_exacta": 811.5363,
        "lipidmaps_id": "LMGP03010010",
        "swisslipids_id": "SLM:000001824",
        "hmdb_id": "HMDB0011516",
        "chebi_id": "CHEBI:73815",
        "pubchem_cid": "52923023",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)(O)OCC(N)C(=O)O",
        "inchi_key": "KWQFYKLYWAKUPO-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PS 38:4", "LipidBlast"), ("PS(18:0/20:4)", "IUPAC"), ("SAPS", "Comun")]
    },

    # --- FOSFATIDILINOSITOLES (PI) ---
    {
        "abreviatura": "PI(38:4)",
        "abreviatura_lipidblast": "PI 38:4",
        "abreviatura_cadenas": "PI 18:0/20:4",
        "nombre_comun": "1-estearoil-2-araquidonoilfosfatidilinositol (SAPI)",
        "nombre_sistematico": "1-octadecanoyl-2-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sn-glycero-3-phospho-(1D-myo-inositol)",
        "categoria": "Glycerophospholipids [GP]",
        "clase": "Glycerophosphoinositols [GP06]",
        "subclase": "Diacylglycerophosphoinositols [GP0601]",
        "formula": "C47H83O13P",
        "masa_exacta": 886.5571,
        "lipidmaps_id": "LMGP06010010",
        "swisslipids_id": "SLM:000002440",
        "hmdb_id": "HMDB0012210",
        "chebi_id": "CHEBI:73840",
        "pubchem_cid": "52923050",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)OC(COC(=O)CCCCCCCCCCCCCCCCC)COP(=O)(O)OC1C(O)C(O)C(O)C(O)C1O",
        "inchi_key": "HPMUHGNDGJRJOG-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("PI 38:4", "LipidBlast"), ("PI(18:0/20:4)", "IUPAC"), ("SAPI", "Comun")]
    },

    # --- ESFINGOMIELINAS (SM) ---
    {
        "abreviatura": "SM(d18:1/16:0)",
        "abreviatura_lipidblast": "SM d18:1/16:0",
        "abreviatura_cadenas": "SM 18:1;O2/16:0",
        "nombre_comun": "N-palmitoil-D-eritro-esfingosilfosforilcolina",
        "nombre_sistematico": "N-(hexadecanoyl)-sphing-4-enine-1-phosphocholine",
        "categoria": "Sphingolipids [SP]",
        "clase": "Phosphosphingolipids [SP03]",
        "subclase": "Ceramide phosphocholines (sphingomyelins) [SP0301]",
        "formula": "C39H79N2O6P",
        "masa_exacta": 702.5676,
        "lipidmaps_id": "LMSP03010001",
        "swisslipids_id": "SLM:000000352",
        "hmdb_id": "HMDB0001348",
        "chebi_id": "CHEBI:64716",
        "pubchem_cid": "52923080",
        "smiles": "CCCCCCCCCCCCCCCC(=O)NC(COP(=O)([O-])OCC[N+](C)(C)C)C(O)/C=C/CCCCCCCCCCCCC",
        "inchi_key": "KILNVBNDVJNVNK-SM16-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("SM d18:1/16:0", "LipidBlast"), ("SM(d34:1)", "LIPID_MAPS"), ("SM 34:1", "Shorthand"), ("SM(34:1)", "Canonical"), ("C16:0-SM", "Comun")]
    },
    {
        "abreviatura": "SM(d18:1/18:0)",
        "abreviatura_lipidblast": "SM d18:1/18:0",
        "abreviatura_cadenas": "SM 18:1;O2/18:0",
        "nombre_comun": "N-estearoil-esfingomielina",
        "nombre_sistematico": "N-(octadecanoyl)-sphing-4-enine-1-phosphocholine",
        "categoria": "Sphingolipids [SP]",
        "clase": "Phosphosphingolipids [SP03]",
        "subclase": "Ceramide phosphocholines (sphingomyelins) [SP0301]",
        "formula": "C41H83N2O6P",
        "masa_exacta": 730.5989,
        "lipidmaps_id": "LMSP03010002",
        "swisslipids_id": "SLM:000000353",
        "hmdb_id": "HMDB0001349",
        "chebi_id": "CHEBI:64717",
        "pubchem_cid": "52923081",
        "smiles": "CCCCCCCCCCCCCCCCC(=O)NC(COP(=O)([O-])OCC[N+](C)(C)C)C(O)/C=C/CCCCCCCCCCCCC",
        "inchi_key": "LMSP03010002-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("SM d18:1/18:0", "LipidBlast"), ("SM(d36:1)", "LIPID_MAPS"), ("SM(36:1)", "Canonical"), ("C18:0-SM", "Comun")]
    },
    {
        "abreviatura": "SM(d18:1/24:1)",
        "abreviatura_lipidblast": "SM d18:1/24:1",
        "abreviatura_cadenas": "SM 18:1;O2/24:1(15Z)",
        "nombre_comun": "N-nervonoil-esfingomielina",
        "nombre_sistematico": "N-(15Z-tetracosenoyl)-sphing-4-enine-1-phosphocholine",
        "categoria": "Sphingolipids [SP]",
        "clase": "Phosphosphingolipids [SP03]",
        "subclase": "Ceramide phosphocholines (sphingomyelins) [SP0301]",
        "formula": "C47H93N2O6P",
        "masa_exacta": 812.6771,
        "lipidmaps_id": "LMSP03010005",
        "swisslipids_id": "SLM:000000357",
        "hmdb_id": "HMDB0001353",
        "chebi_id": "CHEBI:64720",
        "pubchem_cid": "52923085",
        "smiles": "CCCCCCCCC/C=C\\CCCCCCCCCCCCCC(=O)NC(COP(=O)([O-])OCC[N+](C)(C)C)C(O)/C=C/CCCCCCCCCCCCC",
        "inchi_key": "LMSP03010005-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("SM d18:1/24:1", "LipidBlast"), ("SM(d42:2)", "LIPID_MAPS"), ("SM(42:2)", "Canonical"), ("C24:1-SM", "Comun")]
    },

    # --- CERAMIDAS (Cer) ---
    {
        "abreviatura": "Cer(d18:1/16:0)",
        "abreviatura_lipidblast": "Cer d18:1/16:0",
        "abreviatura_cadenas": "Cer 18:1;O2/16:0",
        "nombre_comun": "N-palmitoil-D-eritro-esfingosina (Ceramida C16:0)",
        "nombre_sistematico": "N-(hexadecanoyl)-sphing-4-enine",
        "categoria": "Sphingolipids [SP]",
        "clase": "Ceramides [SP02]",
        "subclase": "Ceramides [SP0201]",
        "formula": "C34H67NO3",
        "masa_exacta": 537.5121,
        "lipidmaps_id": "LMSP02010001",
        "swisslipids_id": "SLM:000000115",
        "hmdb_id": "HMDB0004948",
        "chebi_id": "CHEBI:52639",
        "pubchem_cid": "5288544",
        "smiles": "CCCCCCCCCCCCCCCC(=O)NC(CO)C(O)/C=C/CCCCCCCCCCCCC",
        "inchi_key": "KILNVBNDVJNVNK-CER16-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("Cer d18:1/16:0", "LipidBlast"), ("Cer(d34:1)", "LIPID_MAPS"), ("C16 Ceramide", "Comun")]
    },
    {
        "abreviatura": "Cer(d18:1/24:0)",
        "abreviatura_lipidblast": "Cer d18:1/24:0",
        "abreviatura_cadenas": "Cer 18:1;O2/24:0",
        "nombre_comun": "N-lignoceroil-esfingosina (Ceramida C24:0)",
        "nombre_sistematico": "N-(tetracosanoyl)-sphing-4-enine",
        "categoria": "Sphingolipids [SP]",
        "clase": "Ceramides [SP02]",
        "subclase": "Ceramides [SP0201]",
        "formula": "C42H83NO3",
        "masa_exacta": 649.6373,
        "lipidmaps_id": "LMSP02010004",
        "swisslipids_id": "SLM:000000119",
        "hmdb_id": "HMDB0004951",
        "chebi_id": "CHEBI:52642",
        "pubchem_cid": "5288547",
        "smiles": "CCCCCCCCCCCCCCCCCCCCCCCC(=O)NC(CO)C(O)/C=C/CCCCCCCCCCCCC",
        "inchi_key": "LMSP02010004-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("Cer d18:1/24:0", "LipidBlast"), ("Cer(d42:1)", "LIPID_MAPS"), ("C24 Ceramide", "Comun")]
    },

    # --- TRIACILGLICEROLES (TG / TAG) ---
    {
        "abreviatura": "TG(48:0)",
        "abreviatura_lipidblast": "TG 48:0",
        "abreviatura_cadenas": "TG 16:0_16:0_16:0",
        "nombre_comun": "Tripalmitina",
        "nombre_sistematico": "1,2,3-trihexadecanoylglycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Triacylglycerols [GL03]",
        "subclase": "Triacylglycerols [GL0301]",
        "formula": "C51H98O6",
        "masa_exacta": 806.7363,
        "lipidmaps_id": "LMGL03010002",
        "swisslipids_id": "SLM:000003001",
        "hmdb_id": "HMDB0005378",
        "chebi_id": "CHEBI:28731",
        "pubchem_cid": "11147",
        "smiles": "CCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCC",
        "inchi_key": "IPCSVZSSVZVIGE-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("TG 48:0", "LipidBlast"), ("TAG 48:0", "Dialect"), ("Tripalmitin", "Comun"), ("TG(16:0/16:0/16:0)", "IUPAC")]
    },
    {
        "abreviatura": "TG(52:2)",
        "abreviatura_lipidblast": "TG 52:2",
        "abreviatura_cadenas": "TG 16:0_18:1_18:1",
        "nombre_comun": "1-palmitoil-2,3-dioleoilglicerol",
        "nombre_sistematico": "1-hexadecanoyl-2,3-di-(9Z-octadecenoyl)-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Triacylglycerols [GL03]",
        "subclase": "Triacylglycerols [GL0301]",
        "formula": "C55H102O6",
        "masa_exacta": 858.7676,
        "lipidmaps_id": "LMGL03010045",
        "swisslipids_id": "SLM:000003110",
        "hmdb_id": "HMDB0005412",
        "chebi_id": "CHEBI:75200",
        "pubchem_cid": "52923150",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
        "inchi_key": "LMGL03010045-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("TG 52:2", "LipidBlast"), ("TAG 52:2", "Dialect"), ("TG 16:0_18:1_18:1", "LipidBlast")]
    },
    {
        "abreviatura": "TG(54:3)",
        "abreviatura_lipidblast": "TG 54:3",
        "abreviatura_cadenas": "TG 18:1_18:1_18:1",
        "nombre_comun": "Trioleína",
        "nombre_sistematico": "1,2,3-tri-(9Z-octadecenoyl)-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Triacylglycerols [GL03]",
        "subclase": "Triacylglycerols [GL0301]",
        "formula": "C57H104O6",
        "masa_exacta": 884.7833,
        "lipidmaps_id": "LMGL03010007",
        "swisslipids_id": "SLM:000003150",
        "hmdb_id": "HMDB0005439",
        "chebi_id": "CHEBI:28487",
        "pubchem_cid": "5497163",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(COC(=O)CCCCCCC/C=C\\CCCCCCCC)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
        "inchi_key": "AYFVYJQAPQTCCC-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("TG 54:3", "LipidBlast"), ("TAG 54:3", "Dialect"), ("Triolein", "Comun"), ("TG(18:1/18:1/18:1)", "IUPAC")]
    },

    # --- DIACILGLICEROLES (DG / DAG) ---
    {
        "abreviatura": "DG(34:1)",
        "abreviatura_lipidblast": "DG 34:1",
        "abreviatura_cadenas": "DG 16:0_18:1",
        "nombre_comun": "1-palmitoil-2-oleoilglicerol",
        "nombre_sistematico": "1-hexadecanoyl-2-(9Z-octadecenoyl)-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Diacylglycerols [GL02]",
        "subclase": "Diacylglycerols [GL0201]",
        "formula": "C37H70O5",
        "masa_exacta": 594.5223,
        "lipidmaps_id": "LMGL02010015",
        "swisslipids_id": "SLM:000002850",
        "hmdb_id": "HMDB0007120",
        "chebi_id": "CHEBI:74500",
        "pubchem_cid": "52923120",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC(CO)COC(=O)CCCCCCCCCCCCCCC",
        "inchi_key": "LMGL02010015-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("DG 34:1", "LipidBlast"), ("DAG 34:1", "Dialect"), ("DG(16:0/18:1)", "IUPAC")]
    },
    {
        "abreviatura": "DG(36:2)",
        "abreviatura_lipidblast": "DG 36:2",
        "abreviatura_cadenas": "DG 18:1_18:1",
        "nombre_comun": "1,2-dioleoilglicerol",
        "nombre_sistematico": "1,2-di-(9Z-octadecenoyl)-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Diacylglycerols [GL02]",
        "subclase": "Diacylglycerols [GL0201]",
        "formula": "C39H72O5",
        "masa_exacta": 620.5380,
        "lipidmaps_id": "LMGL02010020",
        "swisslipids_id": "SLM:000002870",
        "hmdb_id": "HMDB0007135",
        "chebi_id": "CHEBI:74510",
        "pubchem_cid": "52923125",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(CO)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
        "inchi_key": "LMGL02010020-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("DG 36:2", "LipidBlast"), ("DAG 36:2", "Dialect"), ("DG(18:1/18:1)", "IUPAC")]
    },

    # --- ÉSTERES DE COLESTEROL (CE) ---
    {
        "abreviatura": "CE(16:0)",
        "abreviatura_lipidblast": "CE 16:0",
        "abreviatura_cadenas": "CE 16:0",
        "nombre_comun": "Palmitato de colesterilo",
        "nombre_sistematico": "cholest-5-en-3beta-yl hexadecanoate",
        "categoria": "Sterol Lipids [ST]",
        "clase": "Sterols [ST01]",
        "subclase": "Cholesterol and derivatives [ST0101]",
        "formula": "C43H76O2",
        "masa_exacta": 624.5845,
        "lipidmaps_id": "LMST01010002",
        "swisslipids_id": "SLM:000003501",
        "hmdb_id": "HMDB0000885",
        "chebi_id": "CHEBI:39420",
        "pubchem_cid": "92110",
        "smiles": "CCCCCCCCCCCCCCCC(=O)OC1CCC2(C)C(=CCC3C2CCC4(C)C3CCC4C(C)CCCC(C)C)C1",
        "inchi_key": "COYHGRLTNLOHCA-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("CE 16:0", "LipidBlast"), ("Cholesteryl palmitate", "Comun")]
    },
    {
        "abreviatura": "CE(18:1)",
        "abreviatura_lipidblast": "CE 18:1",
        "abreviatura_cadenas": "CE 18:1(9Z)",
        "nombre_comun": "Oleato de colesterilo",
        "nombre_sistematico": "cholest-5-en-3beta-yl (9Z-octadecenoate)",
        "categoria": "Sterol Lipids [ST]",
        "clase": "Sterols [ST01]",
        "subclase": "Cholesterol and derivatives [ST0101]",
        "formula": "C45H78O2",
        "masa_exacta": 650.6002,
        "lipidmaps_id": "LMST01010004",
        "swisslipids_id": "SLM:000003503",
        "hmdb_id": "HMDB0000674",
        "chebi_id": "CHEBI:39422",
        "pubchem_cid": "5284561",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC1CCC2(C)C(=CCC3C2CCC4(C)C3CCC4C(C)CCCC(C)C)C1",
        "inchi_key": "WZPBWNSPDCXACW-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("CE 18:1", "LipidBlast"), ("Cholesteryl oleate", "Comun")]
    },

    # --- ÁCIDOS GRASOS LIBRES (FA) ---
    {
        "abreviatura": "FA(16:0)",
        "abreviatura_lipidblast": "FA 16:0",
        "abreviatura_cadenas": "FA 16:0",
        "nombre_comun": "Ácido palmítico",
        "nombre_sistematico": "hexadecanoic acid",
        "categoria": "Fatty Acyls [FA]",
        "clase": "Fatty Acids and Conjugates [FA01]",
        "subclase": "Straight chain fatty acids [FA0101]",
        "formula": "C16H32O2",
        "masa_exacta": 256.2402,
        "lipidmaps_id": "LMFA01010001",
        "swisslipids_id": "SLM:000000001",
        "hmdb_id": "HMDB0000220",
        "chebi_id": "CHEBI:15756",
        "pubchem_cid": "985",
        "smiles": "CCCCCCCCCCCCCCCC(=O)O",
        "inchi_key": "IPCSVZSSVZVIGE-FA16-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("FA 16:0", "LipidBlast"), ("Palmitic acid", "Comun"), ("C16:0", "Shorthand")]
    },
    {
        "abreviatura": "FA(18:1)",
        "abreviatura_lipidblast": "FA 18:1",
        "abreviatura_cadenas": "FA 18:1(9Z)",
        "nombre_comun": "Ácido oleico",
        "nombre_sistematico": "(9Z)-octadec-9-enoic acid",
        "categoria": "Fatty Acyls [FA]",
        "clase": "Fatty Acids and Conjugates [FA01]",
        "subclase": "Straight chain fatty acids [FA0101]",
        "formula": "C18H34O2",
        "masa_exacta": 282.2559,
        "lipidmaps_id": "LMFA01010006",
        "swisslipids_id": "SLM:000000004",
        "hmdb_id": "HMDB0000207",
        "chebi_id": "CHEBI:16196",
        "pubchem_cid": "445639",
        "smiles": "CCCCCCCC/C=C\\CCCCCCCC(=O)O",
        "inchi_key": "ZQPPMHVWECSIRJ-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("FA 18:1", "LipidBlast"), ("Oleic acid", "Comun"), ("C18:1", "Shorthand")]
    },
    {
        "abreviatura": "FA(20:4)",
        "abreviatura_lipidblast": "FA 20:4",
        "abreviatura_cadenas": "FA 20:4(5Z,8Z,11Z,14Z)",
        "nombre_comun": "Ácido araquidónico (AA)",
        "nombre_sistematico": "(5Z,8Z,11Z,14Z)-icosa-5,8,11,14-tetraenoic acid",
        "categoria": "Fatty Acyls [FA]",
        "clase": "Fatty Acids and Conjugates [FA01]",
        "subclase": "Straight chain fatty acids [FA0101]",
        "formula": "C20H32O2",
        "masa_exacta": 304.2402,
        "lipidmaps_id": "LMFA01010015",
        "swisslipids_id": "SLM:000000010",
        "hmdb_id": "HMDB0001043",
        "chebi_id": "CHEBI:15843",
        "pubchem_cid": "444899",
        "smiles": "CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)O",
        "inchi_key": "YZXBAPSDXZZRGB-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("FA 20:4", "LipidBlast"), ("Arachidonic acid", "Comun"), ("AA", "Comun")]
    },
    {
        "abreviatura": "FA(22:6)",
        "abreviatura_lipidblast": "FA 22:6",
        "abreviatura_cadenas": "FA 22:6(4Z,7Z,10Z,13Z,16Z,19Z)",
        "nombre_comun": "Ácido docosahexaenoico (DHA)",
        "nombre_sistematico": "(4Z,7Z,10Z,13Z,16Z,19Z)-docosa-4,7,10,13,16,19-hexaenoic acid",
        "categoria": "Fatty Acyls [FA]",
        "clase": "Fatty Acids and Conjugates [FA01]",
        "subclase": "Straight chain fatty acids [FA0101]",
        "formula": "C22H32O2",
        "masa_exacta": 328.2402,
        "lipidmaps_id": "LMFA01010022",
        "swisslipids_id": "SLM:000000015",
        "hmdb_id": "HMDB0002183",
        "chebi_id": "CHEBI:28125",
        "pubchem_cid": "445580",
        "smiles": "CC/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\C/C=C\\CCC(=O)O",
        "inchi_key": "MBMBGCFOFBJSGT-UHFFFAOYSA-N",
        "fuentes": "LipidBlast, LIPID MAPS, SwissLipids, HMDB",
        "sinonimos": [("FA 22:6", "LipidBlast"), ("Docosahexaenoic acid", "Comun"), ("DHA", "Comun")]
    },

    # --- GLICOLÍPIDOS / ACILDIACILGLICERIL GLUCURÓNIDOS (ADGGA - LipidBlast / Algas y Plantas) ---
    {
        "abreviatura": "ADGGA",
        "abreviatura_lipidblast": "ADGGA",
        "abreviatura_cadenas": "Acyl-DAG-GlcA",
        "nombre_comun": "Acildiacilgliceril glucurónido (Acyl diacylglyceryl glucuronide)",
        "nombre_sistematico": "3-O-(acyl-beta-D-glucuronosyl)-1,2-diacyl-sn-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Glycosyldiacylglycerols [GL05]",
        "subclase": "Acyl diacylglyceryl glucuronides (ADGGA) [GL0504]",
        "formula": "Variable (CnH2n-2xO12)",
        "masa_exacta": 0.0,
        "lipidmaps_id": "GL0504 (Clase)",
        "swisslipids_id": "SLM:ADGGA",
        "hmdb_id": "-",
        "chebi_id": "-",
        "pubchem_cid": "-",
        "smiles": "-",
        "inchi_key": "-",
        "fuentes": "LipidBlast (Fiehn Lab), MS-DIAL",
        "sinonimos": [("ADGGA", "LipidBlast"), ("acyl diacylglyceryl glucuronide", "Comun"), ("Acyl-GlcADG", "Dialect"), ("Acylated glucuronosyldiacylglycerol", "IUPAC")]
    },
    {
        "abreviatura": "ADGGA(50:2)",
        "abreviatura_lipidblast": "ADGGA 50:2",
        "abreviatura_cadenas": "ADGGA 16:0_18:2_16:0",
        "nombre_comun": "Acil-diacilgliceril glucurónido (50:2)",
        "nombre_sistematico": "3-O-(hexadecanoyl-beta-D-glucuronosyl)-1-hexadecanoyl-2-(9Z,12Z-octadecadienoyl)-sn-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Glycosyldiacylglycerols [GL05]",
        "subclase": "Acyl diacylglyceryl glucuronides (ADGGA) [GL0504]",
        "formula": "C59H106O12",
        "masa_exacta": 1006.7685,
        "lipidmaps_id": "-",
        "swisslipids_id": "-",
        "hmdb_id": "-",
        "chebi_id": "-",
        "pubchem_cid": "-",
        "smiles": "-",
        "inchi_key": "-",
        "fuentes": "LipidBlast (Fiehn Lab), MS-DIAL",
        "sinonimos": [("ADGGA 50:2", "LipidBlast"), ("ADGGA 16:0_18:2_16:0", "LipidBlast"), ("ADGGA(16:0/18:2/16:0)", "IUPAC")]
    },
    {
        "abreviatura": "ADGGA(52:3)",
        "abreviatura_lipidblast": "ADGGA 52:3",
        "abreviatura_cadenas": "ADGGA 16:0_18:3_18:0",
        "nombre_comun": "Acil-diacilgliceril glucurónido (52:3)",
        "nombre_sistematico": "3-O-(octadecanoyl-beta-D-glucuronosyl)-1-hexadecanoyl-2-(9Z,12Z,15Z-octadecatrienoyl)-sn-glycerol",
        "categoria": "Glycerolipids [GL]",
        "clase": "Glycosyldiacylglycerols [GL05]",
        "subclase": "Acyl diacylglyceryl glucuronides (ADGGA) [GL0504]",
        "formula": "C61H108O12",
        "masa_exacta": 1032.7841,
        "lipidmaps_id": "-",
        "swisslipids_id": "-",
        "hmdb_id": "-",
        "chebi_id": "-",
        "pubchem_cid": "-",
        "smiles": "-",
        "inchi_key": "-",
        "fuentes": "LipidBlast (Fiehn Lab), MS-DIAL",
        "sinonimos": [("ADGGA 52:3", "LipidBlast"), ("ADGGA 16:0_18:3_18:0", "LipidBlast"), ("ADGGA(16:0/18:3/18:0)", "IUPAC")]
    },

    # --- 28 CLASES DE LIPIDBLAST Y LIPIDÓMICA ---
    {   'abreviatura': 'AHexCer',
        'abreviatura_cadenas': 'Acyl-Hex-Cer',
        'abreviatura_lipidblast': 'AHexCer',
        'categoria': 'Sphingolipids [SP]',
        'chebi_id': None,
        'clase': 'Neutral glycosphingolipids [SP05]',
        'formula': 'Variable (Esfingolípido acil-glicosilado)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'SP0501',
        'masa_exacta': 0.0,
        'nombre_comun': 'Acil hexosilceramida (Acyl hexosylceramide)',
        'nombre_sistematico': '1-O-(acyl-beta-D-hexosyl)-N-acylsphingosine',
        'pubchem_cid': None,
        'sinonimos': [('AcylHexCer', 'Dialect'), ('Acyl hexosylceramide', 'Comun'), ('Acyl-Hex-Cer', 'MolecularSpecies')],
        'smiles': None,
        'subclase': 'Acyl hexosylceramides [SP0501]',
        'swisslipids_id': 'SLM:AHexCer'},
    {   'abreviatura': 'BA',
        'abreviatura_cadenas': 'Bile Acid core',
        'abreviatura_lipidblast': 'BA',
        'categoria': 'Sterol Lipids [ST]',
        'chebi_id': None,
        'clase': 'Bile acids and derivatives [ST04]',
        'formula': 'C24H40O3 - C26H45NO7S',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0000619',
        'inchi_key': None,
        'lipidmaps_id': 'ST04',
        'masa_exacta': 0.0,
        'nombre_comun': 'Ácidos biliares (Bile Acids and conjugates)',
        'nombre_sistematico': 'Cholanoic acid derivatives and glycine/taurine conjugates',
        'pubchem_cid': None,
        'sinonimos': [   ('Bile Acid', 'Comun'),
                         ('Ácido biliar', 'Comun'),
                         ('Bile Acid core', 'MolecularSpecies'),
                         ('Bile acids', 'Comun')],
        'smiles': None,
        'subclase': 'Bile acids, alcohols and derivatives [ST0401]',
        'swisslipids_id': 'SLM:BA'},
    {   'abreviatura': 'CAR',
        'abreviatura_cadenas': 'Acyl-Carnitine',
        'abreviatura_lipidblast': 'CAR',
        'categoria': 'Fatty Acyls [FA]',
        'chebi_id': None,
        'clase': 'Fatty acid conjugates [FA01]',
        'formula': 'Variable (CnH2n+1NO4)',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0000222',
        'inchi_key': None,
        'lipidmaps_id': 'FA0105',
        'masa_exacta': 0.0,
        'nombre_comun': 'Acilcarnitinas (Acylcarnitines)',
        'nombre_sistematico': 'O-acyl-L-carnitine',
        'pubchem_cid': None,
        'sinonimos': [   ('Acyl-Carnitine', 'MolecularSpecies'),
                         ('Acylcarnitine', 'Comun'),
                         ('ACar', 'Dialect'),
                         ('Acilcarnitina', 'Comun')],
        'smiles': None,
        'subclase': 'Acyl carnitines [FA0105]',
        'swisslipids_id': 'SLM:CAR'},
    {   'abreviatura': 'Cer',
        'abreviatura_cadenas': 'N-Acyl-sphingoid base',
        'abreviatura_lipidblast': 'Cer',
        'categoria': 'Sphingolipids [SP]',
        'chebi_id': None,
        'clase': 'Ceramides [SP02]',
        'formula': 'Variable (CnH2n-1NO3)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0004948',
        'inchi_key': None,
        'lipidmaps_id': 'SP0201',
        'masa_exacta': 0.0,
        'nombre_comun': 'Ceramidas (Ceramides)',
        'nombre_sistematico': 'N-(acyl)-sphing-4-enine',
        'pubchem_cid': None,
        'sinonimos': [   ('Ceramides', 'Comun'),
                         ('Ceramide', 'Comun'),
                         ('N-Acyl-sphingoid base', 'MolecularSpecies'),
                         ('Ceramida', 'Comun')],
        'smiles': None,
        'subclase': 'Ceramides [SP0201]',
        'swisslipids_id': 'SLM:Cer'},
    {   'abreviatura': 'CoQ3',
        'abreviatura_cadenas': 'CoQ(3)',
        'abreviatura_lipidblast': 'CoQ3',
        'categoria': 'Prenol Lipids [PR]',
        'chebi_id': None,
        'clase': 'Quinones and hydroquinones [PR02]',
        'formula': 'C24H34O4',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0001073',
        'inchi_key': None,
        'lipidmaps_id': 'LMPR02010003',
        'masa_exacta': 386.2457,
        'nombre_comun': 'Coenzima Q3 / Ubiquinona-3 (Coenzyme Q3)',
        'nombre_sistematico': '2-(3,7,11-trimethyl-dodeca-2,6,10-trienyl)-5,6-dimethoxy-3-methyl-[1,4]benzoquinone',
        'pubchem_cid': None,
        'sinonimos': [   ('CoQ(3)', 'Dialect'),
                         ('CoQ(3)', 'MolecularSpecies'),
                         ('Coenzyme Q3', 'Comun'),
                         ('Ubiquinone-3', 'Comun')],
        'smiles': None,
        'subclase': 'Ubiquinones [PR0201]',
        'swisslipids_id': 'SLM:CoQ3'},
    {   'abreviatura': 'DG',
        'abreviatura_cadenas': '1,2-diacyl-sn-glycerol',
        'abreviatura_lipidblast': 'DG',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Diacylglycerols [GL02]',
        'formula': 'Variable (CnH2n-2xO5)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0007120',
        'inchi_key': None,
        'lipidmaps_id': 'GL0201',
        'masa_exacta': 0.0,
        'nombre_comun': 'Diacilgliceroles (Diacylglycerols / DAG)',
        'nombre_sistematico': '1,2-diacyl-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('1,2-diacyl-sn-glycerol', 'MolecularSpecies'),
                         ('DAG', 'Dialect'),
                         ('Diacilglicerol', 'Comun'),
                         ('Diacylglycerol', 'Comun')],
        'smiles': None,
        'subclase': '1,2-Diacylglycerols [GL0201]',
        'swisslipids_id': 'SLM:DG'},
    {   'abreviatura': 'DG O-',
        'abreviatura_cadenas': '1-O-alkyl-2-acyl-glycerol',
        'abreviatura_lipidblast': 'DG O-',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Diacylglycerols [GL02]',
        'formula': 'Variable (CnH2n-2xO4)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0202',
        'masa_exacta': 0.0,
        'nombre_comun': 'Alquil-acilgliceroles / Éter diacilglicerol (Alkylacylglycerols / Plasmanyl-DG)',
        'nombre_sistematico': '1-O-alkyl-2-acyl-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('1-O-alkyl-2-acyl-glycerol', 'MolecularSpecies'),
                         ('Ether DG', 'Comun'),
                         ('Plasmanyl-DG', 'Dialect'),
                         ('Alkylacylglycerol', 'Comun')],
        'smiles': None,
        'subclase': '1-Alkyl,2-acylglycerols [GL0202]',
        'swisslipids_id': 'SLM:DGO'},
    {   'abreviatura': 'DGDG O-',
        'abreviatura_cadenas': '1-O-alkyl-2-acyl-3-digalactosyl-glycerol',
        'abreviatura_lipidblast': 'DGDG O-',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Glycosyldiacylglycerols [GL05]',
        'formula': 'Variable (Glicolípido éter cloroplástico)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0502',
        'masa_exacta': 0.0,
        'nombre_comun': 'Éter digalactosildiacilglicerol (Digalactosylalkylacylglycerol / Plasmanyl-DGDG)',
        'nombre_sistematico': '1-O-alkyl-2-acyl-3-O-(alpha-D-galactosyl-1->6-beta-D-galactosyl)-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Plasmanyl-DGDG', 'Dialect'),
                         ('1-O-alkyl-2-acyl-3-digalactosyl-glycerol', 'MolecularSpecies'),
                         ('Digalactosylalkylacylglycerol', 'Comun')],
        'smiles': None,
        'subclase': 'Digalactosyldiacylglycerols [GL0502]',
        'swisslipids_id': 'SLM:DGDGO'},
    {   'abreviatura': 'DGTS',
        'abreviatura_cadenas': '1,2-diacyl-3-O-homoserine-glycerol',
        'abreviatura_lipidblast': 'DGTS',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Betaine lipids [GL06]',
        'formula': 'Variable (CnH2n-2xNO7)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0601',
        'masa_exacta': 0.0,
        'nombre_comun': 'Diacilgliceril trimetilhomoserina (Diacylglyceryl trimethylhomoserine)',
        'nombre_sistematico': "1,2-diacyl-3-O-(4'-(N,N,N-trimethyl)-homoserine)-glycerol",
        'pubchem_cid': None,
        'sinonimos': [   ('DGTA/DGTS', 'Dialect'),
                         ('Betaine lipid DGTS', 'Comun'),
                         ('1,2-diacyl-3-O-homoserine-glycerol', 'MolecularSpecies')],
        'smiles': None,
        'subclase': 'Diacylglyceryl trimethylhomoserines [GL0601]',
        'swisslipids_id': 'SLM:DGTS'},
    {   'abreviatura': 'LDGCC',
        'abreviatura_cadenas': '1-acyl-3-O-DGCC-glycerol',
        'abreviatura_lipidblast': 'LDGCC',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Betaine lipids [GL06]',
        'formula': 'Variable (Lípido betaínico liso)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0602',
        'masa_exacta': 0.0,
        'nombre_comun': 'Liso-diacilgliceril carboxihidroximetilcolina (LysoDGCC / Lyso-diacylglyceryl '
                        'carboxyhydroxymethylcholine)',
        'nombre_sistematico': '1-acyl-3-O-carboxyhydroxymethylcholine-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [('Lyso-DGCC', 'Comun'), ('1-acyl-3-O-DGCC-glycerol', 'MolecularSpecies'), ('LysoDGCC', 'Dialect')],
        'smiles': None,
        'subclase': 'Lyso-diacylglyceryl carboxyhydroxymethylcholines [GL0602]',
        'swisslipids_id': 'SLM:LDGCC'},
    {   'abreviatura': 'LPC',
        'abreviatura_cadenas': '1-acyl-sn-glycero-3-phosphocholine',
        'abreviatura_lipidblast': 'lysoPC',
        'categoria': 'Glycerophospholipids [GP]',
        'chebi_id': None,
        'clase': 'Glycerophosphocholines [GP01]',
        'formula': 'Variable (CnH2n+2NO7P)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0010382',
        'inchi_key': None,
        'lipidmaps_id': 'GP0105',
        'masa_exacta': 0.0,
        'nombre_comun': 'Lisofosfatidilcolinas (Lysophosphatidylcholines / lysoPC)',
        'nombre_sistematico': '1-acyl-sn-glycero-3-phosphocholine',
        'pubchem_cid': None,
        'sinonimos': [   ('Lysophosphatidylcholine', 'Comun'),
                         ('Lisofosfatidilcolina', 'Comun'),
                         ('1-acyl-sn-glycero-3-phosphocholine', 'MolecularSpecies'),
                         ('lysoPC', 'LipidBlast')],
        'smiles': None,
        'subclase': 'Monoacylglycerophosphocholines [GP0105]',
        'swisslipids_id': 'SLM:LPC'},
    {   'abreviatura': 'LPC O-',
        'abreviatura_cadenas': '1-O-alkyl-sn-glycero-3-phosphocholine',
        'abreviatura_lipidblast': 'LPC O-',
        'categoria': 'Glycerophospholipids [GP]',
        'chebi_id': None,
        'clase': 'Glycerophosphocholines [GP01]',
        'formula': 'Variable (CnH2n+4NO6P)',
        'fuentes': 'LipidBlast, LIPID MAPS',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GP0106',
        'masa_exacta': 0.0,
        'nombre_comun': 'Alquil-lisofosfatidilcolina / Lyso-PAF (Alkyl-lysophosphatidylcholine / Plasmanyl-LPC)',
        'nombre_sistematico': '1-O-alkyl-sn-glycero-3-phosphocholine',
        'pubchem_cid': None,
        'sinonimos': [   ('lysoPC O-', 'Dialect'),
                         ('1-O-alkyl-sn-glycero-3-phosphocholine', 'MolecularSpecies'),
                         ('Plasmanyl-LPC', 'Comun'),
                         ('Lyso-PAF', 'Comun')],
        'smiles': None,
        'subclase': 'Monoalkylglycerophosphocholines [GP0106]',
        'swisslipids_id': 'SLM:LPCO'},
    {   'abreviatura': 'LPE P-',
        'abreviatura_cadenas': '1-O-(1Z-alkenyl)-sn-glycero-3-phosphoethanolamine',
        'abreviatura_lipidblast': 'LPE P-',
        'categoria': 'Glycerophospholipids [GP]',
        'chebi_id': None,
        'clase': 'Glycerophosphoethanolamines [GP02]',
        'formula': 'Variable (Lisoplasmalógeno PE)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GP0207',
        'masa_exacta': 0.0,
        'nombre_comun': 'Plasmenil-lisofosfatidiletanolamina (Plasmenyl-lysophosphatidylethanolamine)',
        'nombre_sistematico': '1-O-(1Z-alkenyl)-sn-glycero-3-phosphoethanolamine',
        'pubchem_cid': None,
        'sinonimos': [   ('1-O-(1Z-alkenyl)-sn-glycero-3-phosphoethanolamine', 'MolecularSpecies'),
                         ('Plasmenyl-LPE', 'Comun'),
                         ('Lyso-plasmalogen PE', 'Comun'),
                         ('lysoPE P-', 'Dialect')],
        'smiles': None,
        'subclase': 'Monoalkenylglycerophosphoethanolamines [GP0207]',
        'swisslipids_id': 'SLM:LPEP'},
    {   'abreviatura': 'MG',
        'abreviatura_cadenas': '1-acyl-sn-glycerol',
        'abreviatura_lipidblast': 'MG',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Monoacylglycerols [GL01]',
        'formula': 'Variable (CnH2nO4)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0011554',
        'inchi_key': None,
        'lipidmaps_id': 'GL0101',
        'masa_exacta': 0.0,
        'nombre_comun': 'Monoacilgliceroles (Monoacylglycerols / MAG)',
        'nombre_sistematico': '1-acyl-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Monoacylglycerol', 'Comun'),
                         ('1-acyl-sn-glycerol', 'MolecularSpecies'),
                         ('Monoacilglicerol', 'Comun'),
                         ('MAG', 'Dialect')],
        'smiles': None,
        'subclase': '1-Monoacylglycerols [GL0101]',
        'swisslipids_id': 'SLM:MG'},
    {   'abreviatura': 'MGDG O-',
        'abreviatura_cadenas': '1-O-alkyl-2-acyl-3-monogalactosyl-glycerol',
        'abreviatura_lipidblast': 'MGDG O-',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Glycosyldiacylglycerols [GL05]',
        'formula': 'Variable (Glicolípido éter cloroplástico)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0501',
        'masa_exacta': 0.0,
        'nombre_comun': 'Éter monogalactosildiacilglicerol (Monogalactosylalkylacylglycerol / Plasmanyl-MGDG)',
        'nombre_sistematico': '1-O-alkyl-2-acyl-3-O-(beta-D-galactopyranosyl)-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Monogalactosylalkylacylglycerol', 'Comun'),
                         ('1-O-alkyl-2-acyl-3-monogalactosyl-glycerol', 'MolecularSpecies'),
                         ('Plasmanyl-MGDG', 'Dialect')],
        'smiles': None,
        'subclase': 'Monogalactosyldiacylglycerols [GL0501]',
        'swisslipids_id': 'SLM:MGDGO'},
    {   'abreviatura': 'NAE',
        'abreviatura_cadenas': 'N-acyl-ethanolamine',
        'abreviatura_lipidblast': 'NAE',
        'categoria': 'Fatty Acyls [FA]',
        'chebi_id': None,
        'clase': 'Fatty amides [FA08]',
        'formula': 'Variable (CnH2n+1NO2)',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0002064',
        'inchi_key': None,
        'lipidmaps_id': 'FA0804',
        'masa_exacta': 0.0,
        'nombre_comun': 'N-aciletanolaminas / Endocannabinoides (N-Acylethanolamines)',
        'nombre_sistematico': 'N-(acyl)-ethanolamine',
        'pubchem_cid': None,
        'sinonimos': [   ('Anandamide family', 'Comun'),
                         ('N-acyl-ethanolamine', 'MolecularSpecies'),
                         ('N-acylethanolamine', 'Comun')],
        'smiles': None,
        'subclase': 'N-acyl ethanolamides [FA0804]',
        'swisslipids_id': 'SLM:NAE'},
    {   'abreviatura': 'NAGly',
        'abreviatura_cadenas': 'N-acyl-glycine',
        'abreviatura_lipidblast': 'NAGly',
        'categoria': 'Fatty Acyls [FA]',
        'chebi_id': None,
        'clase': 'Fatty amides [FA08]',
        'formula': 'Variable (CnH2n-1NO3)',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0000832',
        'inchi_key': None,
        'lipidmaps_id': 'FA0801',
        'masa_exacta': 0.0,
        'nombre_comun': 'N-acilglicinas (N-Acylglycines)',
        'nombre_sistematico': 'N-(acyl)-glycine',
        'pubchem_cid': None,
        'sinonimos': [('N-acylglycine', 'Comun'), ('N-acyl glycine', 'Comun'), ('N-acyl-glycine', 'MolecularSpecies')],
        'smiles': None,
        'subclase': 'N-acyl glycines [FA0801]',
        'swisslipids_id': 'SLM:NAGly'},
    {   'abreviatura': 'NAGlySer',
        'abreviatura_cadenas': 'N-acyl-glycyl-serine',
        'abreviatura_lipidblast': 'NAGlySer',
        'categoria': 'Fatty Acyls [FA]',
        'chebi_id': None,
        'clase': 'Fatty amides [FA08]',
        'formula': 'Variable (Lipoaminoácido dipeptídico)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'FA0807',
        'masa_exacta': 0.0,
        'nombre_comun': 'N-acilglicilserinas (N-Acylglycylserines)',
        'nombre_sistematico': 'N-(N-acylglycyl)-L-serine',
        'pubchem_cid': None,
        'sinonimos': [('N-acylglycylserine', 'Comun'), ('N-acyl-glycyl-serine', 'MolecularSpecies')],
        'smiles': None,
        'subclase': 'N-acyl dipeptides [FA0807]',
        'swisslipids_id': 'SLM:NAGlySer'},
    {   'abreviatura': 'NATau',
        'abreviatura_cadenas': 'N-acyl-taurine',
        'abreviatura_lipidblast': 'NATau',
        'categoria': 'Fatty Acyls [FA]',
        'chebi_id': None,
        'clase': 'Fatty amides [FA08]',
        'formula': 'Variable (CnH2n+1NO4S)',
        'fuentes': 'LipidBlast, LIPID MAPS, HMDB',
        'hmdb_id': 'HMDB0013334',
        'inchi_key': None,
        'lipidmaps_id': 'FA0802',
        'masa_exacta': 0.0,
        'nombre_comun': 'N-aciltaurinas (N-Acyltaurines)',
        'nombre_sistematico': '2-(acylamino)ethanesulfonic acid',
        'pubchem_cid': None,
        'sinonimos': [('N-acyltaurine', 'Comun'), ('N-acyl-taurine', 'MolecularSpecies'), ('N-acyl taurine', 'Comun')],
        'smiles': None,
        'subclase': 'N-acyl taurines [FA0802]',
        'swisslipids_id': 'SLM:NATau'},
    {   'abreviatura': 'PC',
        'abreviatura_cadenas': '1,2-diacyl-sn-glycero-3-phosphocholine',
        'abreviatura_lipidblast': 'PC',
        'categoria': 'Glycerophospholipids [GP]',
        'chebi_id': None,
        'clase': 'Glycerophosphocholines [GP01]',
        'formula': 'Variable (CnH2n-2xNO8P)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0007873',
        'inchi_key': None,
        'lipidmaps_id': 'GP0101',
        'masa_exacta': 0.0,
        'nombre_comun': 'Fosfatidilcolinas (Phosphatidylcholines / Lecitinas)',
        'nombre_sistematico': '1,2-diacyl-sn-glycero-3-phosphocholine',
        'pubchem_cid': None,
        'sinonimos': [   ('1,2-diacyl-sn-glycero-3-phosphocholine', 'MolecularSpecies'),
                         ('Lecithin', 'Comun'),
                         ('Phosphatidylcholine', 'Comun'),
                         ('Fosfatidilcolina', 'Comun')],
        'smiles': None,
        'subclase': 'Diacylglycerophosphocholines [GP0101]',
        'swisslipids_id': 'SLM:PC'},
    {   'abreviatura': 'PE',
        'abreviatura_cadenas': '1,2-diacyl-sn-glycero-3-phosphoethanolamine',
        'abreviatura_lipidblast': 'PE',
        'categoria': 'Glycerophospholipids [GP]',
        'chebi_id': None,
        'clase': 'Glycerophosphoethanolamines [GP02]',
        'formula': 'Variable (CnH2n-2xNO8P)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0008912',
        'inchi_key': None,
        'lipidmaps_id': 'GP0201',
        'masa_exacta': 0.0,
        'nombre_comun': 'Fosfatidiletanolaminas (Phosphatidylethanolamines / Cefalinas)',
        'nombre_sistematico': '1,2-diacyl-sn-glycero-3-phosphoethanolamine',
        'pubchem_cid': None,
        'sinonimos': [   ('Fosfatidiletanolamina', 'Comun'),
                         ('1,2-diacyl-sn-glycero-3-phosphoethanolamine', 'MolecularSpecies'),
                         ('Cephalin', 'Comun'),
                         ('Phosphatidylethanolamine', 'Comun')],
        'smiles': None,
        'subclase': 'Diacylglycerophosphoethanolamines [GP0201]',
        'swisslipids_id': 'SLM:PE'},
    {   'abreviatura': 'SL',
        'abreviatura_cadenas': 'Sulfolipids / Sulfatides',
        'abreviatura_lipidblast': 'SL',
        'categoria': 'Sphingolipids [SP]',
        'chebi_id': None,
        'clase': 'Acidic glycosphingolipids [SP06]',
        'formula': 'Variable (Lípido sulfatado)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0013340',
        'inchi_key': None,
        'lipidmaps_id': 'SP0601',
        'masa_exacta': 0.0,
        'nombre_comun': 'Sulfolípidos / Sulfátidos (Sulfolipids / Sulfatides)',
        'nombre_sistematico': 'Sulfated glycolipids or 3-O-sulfo-galactosylceramides',
        'pubchem_cid': None,
        'sinonimos': [   ('Sulfolipids / Sulfatides', 'MolecularSpecies'),
                         ('Sulfatide', 'Comun'),
                         ('Sulfolipid', 'Comun'),
                         ('Sulfolípido', 'Comun')],
        'smiles': None,
        'subclase': 'Sulfoglycosphingolipids (sulfatides) [SP0601]',
        'swisslipids_id': 'SLM:SL'},
    {   'abreviatura': 'SM',
        'abreviatura_cadenas': 'N-acyl-sphingoid-1-phosphocholine',
        'abreviatura_lipidblast': 'SM',
        'categoria': 'Sphingolipids [SP]',
        'chebi_id': None,
        'clase': 'Phosphosphingolipids [SP03]',
        'formula': 'Variable (CnH2n-2xN2O6P)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0001348',
        'inchi_key': None,
        'lipidmaps_id': 'SP0301',
        'masa_exacta': 0.0,
        'nombre_comun': 'Esfingomielinas (Sphingomyelins)',
        'nombre_sistematico': 'N-(acyl)-sphing-4-enine-1-phosphocholine',
        'pubchem_cid': None,
        'sinonimos': [   ('N-acyl-sphingoid-1-phosphocholine', 'MolecularSpecies'),
                         ('Sphingomyelin', 'Comun'),
                         ('Esfingomielina', 'Comun')],
        'smiles': None,
        'subclase': 'Ceramide phosphocholines (sphingomyelins) [SP0301]',
        'swisslipids_id': 'SLM:SM'},
    {   'abreviatura': 'SPB',
        'abreviatura_cadenas': 'Sphingoid base',
        'abreviatura_lipidblast': 'SPB',
        'categoria': 'Sphingolipids [SP]',
        'chebi_id': None,
        'clase': 'Sphingoid bases [SP01]',
        'formula': 'Variable (CnH2n+1NO2)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0000252',
        'inchi_key': None,
        'lipidmaps_id': 'SP0101',
        'masa_exacta': 0.0,
        'nombre_comun': 'Bases esfingoides (Sphingoid bases / Esfingosina, Esfinganina)',
        'nombre_sistematico': '2-amino-1,3-dihydroxyalkane/alkene',
        'pubchem_cid': None,
        'sinonimos': [   ('Sphingoid base', 'Comun'),
                         ('Sphingosine', 'Comun'),
                         ('Esfingosina', 'Comun'),
                         ('Sphingoid base', 'MolecularSpecies')],
        'smiles': None,
        'subclase': 'Sphing-4-enines [SP0101]',
        'swisslipids_id': 'SLM:SPB'},
    {   'abreviatura': 'SQDG',
        'abreviatura_cadenas': '1,2-diacyl-3-sulfoquinovosyl-glycerol',
        'abreviatura_lipidblast': 'SQDG',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Glycosyldiacylglycerols [GL05]',
        'formula': 'Variable (Sulfolípido vegetal/algal)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0503',
        'masa_exacta': 0.0,
        'nombre_comun': 'Sulfoquinovosildiacilglicerol (Sulfoquinovosyldiacylglycerol)',
        'nombre_sistematico': '1,2-diacyl-3-O-(6-sulfo-alpha-D-quinovosyl)-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Plant sulfolipid', 'Comun'),
                         ('1,2-diacyl-3-sulfoquinovosyl-glycerol', 'MolecularSpecies'),
                         ('Sulfoquinovosyldiacylglycerol', 'Comun')],
        'smiles': None,
        'subclase': 'Sulfoquinovosyldiacylglycerols [GL0503]',
        'swisslipids_id': 'SLM:SQDG'},
    {   'abreviatura': 'ST',
        'abreviatura_cadenas': 'Sterol core',
        'abreviatura_lipidblast': 'ST',
        'categoria': 'Sterol Lipids [ST]',
        'chebi_id': None,
        'clase': 'Sterols [ST01]',
        'formula': 'Variable (Lípido esteroide)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0000067',
        'inchi_key': None,
        'lipidmaps_id': 'ST01',
        'masa_exacta': 0.0,
        'nombre_comun': 'Esteroles y derivados (Sterols and steroids)',
        'nombre_sistematico': 'Cyclopenta[a]phenanthrene derivatives',
        'pubchem_cid': None,
        'sinonimos': [   ('Sterols', 'Comun'),
                         ('Esterol', 'Comun'),
                         ('Sterol', 'Comun'),
                         ('Sterol core', 'MolecularSpecies'),
                         ('Esteroles', 'Comun')],
        'smiles': None,
        'subclase': 'Cholesterol and derivatives [ST0101]',
        'swisslipids_id': 'SLM:ST'},
    {   'abreviatura': 'TG',
        'abreviatura_cadenas': '1,2,3-triacyl-sn-glycerol',
        'abreviatura_lipidblast': 'TG',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Triacylglycerols [GL03]',
        'formula': 'Variable (CnH2n-4xO6)',
        'fuentes': 'LipidBlast, LIPID MAPS, SwissLipids, HMDB',
        'hmdb_id': 'HMDB0005378',
        'inchi_key': None,
        'lipidmaps_id': 'GL0301',
        'masa_exacta': 0.0,
        'nombre_comun': 'Triacilgliceroles (Triacylglycerols / TAG / Triglicéridos)',
        'nombre_sistematico': '1,2,3-triacyl-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Triglyceride', 'Comun'),
                         ('TAG', 'Dialect'),
                         ('Triacylglycerol', 'Comun'),
                         ('1,2,3-triacyl-sn-glycerol', 'MolecularSpecies'),
                         ('Triglicérido', 'Comun')],
        'smiles': None,
        'subclase': 'Triacylglycerols [GL0301]',
        'swisslipids_id': 'SLM:TG'},
    {   'abreviatura': 'TG O-',
        'abreviatura_cadenas': '1-O-alkyl-2,3-diacyl-glycerol',
        'abreviatura_lipidblast': 'TG O-',
        'categoria': 'Glycerolipids [GL]',
        'chebi_id': None,
        'clase': 'Triacylglycerols [GL03]',
        'formula': 'Variable (CnH2n-2xO5)',
        'fuentes': 'LipidBlast (Fiehn Lab), MS-DIAL',
        'hmdb_id': '-',
        'inchi_key': None,
        'lipidmaps_id': 'GL0302',
        'masa_exacta': 0.0,
        'nombre_comun': 'Alquil-diacilgliceroles / Éter triacilglicerol (Alkyl-diacylglycerol / Plasmanyl-TG)',
        'nombre_sistematico': '1-O-alkyl-2,3-diacyl-sn-glycerol',
        'pubchem_cid': None,
        'sinonimos': [   ('Alkyldiacylglycerol', 'Comun'),
                         ('Plasmanyl-TG', 'Dialect'),
                         ('1-O-alkyl-2,3-diacyl-glycerol', 'MolecularSpecies'),
                         ('Ether TG', 'Comun')],
        'smiles': None,
        'subclase': '1-Alkyl,2,3-diacylglycerols [GL0302]',
        'swisslipids_id': 'SLM:TGO'}

]


def poblar_catalogo():
    """Ejecuta la inicialización, inserción de lípidos y exportación de archivos."""
    conn = inicializar_bd()
    contador = 0
    for item in LIPIDOS_CATALOGO:
        sinonimos = item.get("sinonimos", [])
        insertar_lipido(conn, item, sinonimos)
        contador += 1

    exportar_archivos(conn)
    conn.close()
    print(f"✅ {DB_NAME} poblada con éxito: {contador} especies lipídicas curadas e integradas.")
    print(f"📁 Archivos generados:")
    print(f"   • SQLite: {DB_FILE.name}")
    print(f"   • CSV:    {CSV_FILE.name}")
    print(f"   • JSON:   {JSON_FILE.name}")


if __name__ == "__main__":
    poblar_catalogo()
